embeddings {
  tensor_name: "mes:00027"
  metadata_path: "00027/mes\\metadata.tsv"
  tensor_path: "00027/mes\\tensors.tsv"
}
embeddings {
  tensor_name: "a\303\261o:00027"
  metadata_path: "00027/a\303\261o\\metadata.tsv"
  tensor_path: "00027/a\303\261o\\tensors.tsv"
}
