embeddings {
  tensor_name: "1:00067"
  metadata_path: "00067/1\\metadata.tsv"
  tensor_path: "00067/1\\tensors.tsv"
}
embeddings {
  tensor_name: "10:00067"
  metadata_path: "00067/10\\metadata.tsv"
  tensor_path: "00067/10\\tensors.tsv"
}
embeddings {
  tensor_name: "11:00067"
  metadata_path: "00067/11\\metadata.tsv"
  tensor_path: "00067/11\\tensors.tsv"
}
embeddings {
  tensor_name: "12:00067"
  metadata_path: "00067/12\\metadata.tsv"
  tensor_path: "00067/12\\tensors.tsv"
}
embeddings {
  tensor_name: "2:00067"
  metadata_path: "00067/2\\metadata.tsv"
  tensor_path: "00067/2\\tensors.tsv"
}
embeddings {
  tensor_name: "3:00067"
  metadata_path: "00067/3\\metadata.tsv"
  tensor_path: "00067/3\\tensors.tsv"
}
embeddings {
  tensor_name: "4:00067"
  metadata_path: "00067/4\\metadata.tsv"
  tensor_path: "00067/4\\tensors.tsv"
}
embeddings {
  tensor_name: "5:00067"
  metadata_path: "00067/5\\metadata.tsv"
  tensor_path: "00067/5\\tensors.tsv"
}
embeddings {
  tensor_name: "6:00067"
  metadata_path: "00067/6\\metadata.tsv"
  tensor_path: "00067/6\\tensors.tsv"
}
embeddings {
  tensor_name: "7:00067"
  metadata_path: "00067/7\\metadata.tsv"
  tensor_path: "00067/7\\tensors.tsv"
}
embeddings {
  tensor_name: "8:00067"
  metadata_path: "00067/8\\metadata.tsv"
  tensor_path: "00067/8\\tensors.tsv"
}
embeddings {
  tensor_name: "9:00067"
  metadata_path: "00067/9\\metadata.tsv"
  tensor_path: "00067/9\\tensors.tsv"
}
